bitgray/bitgray/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tienda/', include('tienda.urls')),
    url(r'^rest/', include('rest.urls', namespace='rest'))
]

bitgray/rest/urls.py
from django.conf.urls import url, include
from views import router

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

bitgray/tienda/urls.py
from django.conf.urls import include, url
import views

urlpatterns = [
	url(r'^$', views.home, name='home'),
	#producto crud
	url(r'producto/$', views.ProductoListView.as_view(), name='producto_list'),
	url(r'producto/add/$', views.ProductoCreate.as_view(), name='producto_add'),
	url(r'producto/(?P<pk>[0-9]+)/$', views.ProductoUpdate.as_view(), name='producto_update'),
	url(r'producto/(?P<pk>[0-9]+)/delete/$', views.ProductoDelete.as_view(), name='producto_delete'),
	
	#cliente crud
	url(r'cliente/$', views.ClienteListView.as_view(), name='cliente_list'),
	url(r'cliente/add/$', views.ClienteCreate.as_view(), name='cliente_add'),
	url(r'cliente/(?P<pk>[0-9]+)/$', views.ClienteUpdate.as_view(), name='cliente_update'),
	url(r'cliente/(?P<pk>[0-9]+)/delete/$', views.ClienteDelete.as_view(), name='cliente_delete'),

	#sede crud
	url(r'sede/$', views.SedeListView.as_view(), name='sede_list'),
	url(r'sede/add/$', views.SedeCreate.as_view(), name='sede_add'),
	url(r'sede/(?P<pk>[0-9]+)/$', views.SedeUpdate.as_view(), name='sede_update'),
	url(r'sede/(?P<pk>[0-9]+)/delete/$', views.SedeDelete.as_view(), name='sede_delete'),

	#compra crud
	url(r'compra/$', views.CompraListView.as_view(), name='compra_list'),
	url(r'compra/add/$', views.CompraCreate.as_view(), name='compra_add'),
	url(r'compra/(?P<pk>[0-9]+)/$', views.CompraUpdate.as_view(), name='compra_update'),
	url(r'compra/(?P<pk>[0-9]+)/delete/$', views.CompraDelete.as_view(), name='compra_delete'),

	#consultar compra clientes
	url(r'consulta/$', views.consulta, name='consulta'),
	url(r'cliente/(?P<pk>[0-9]+)/compras.pdf$', views.cliente_pdf, name='cliente_compras_pdf'),
	url(r'cliente/(?P<pk>[0-9]+)/compras.json$', views.cliente_json, name='cliente_compras_json'),

	#mailer
	url(r'^mailer/$', views.mailer, name='mailer'),
]

bitgray/tienda/models.py
from django.core.urlresolvers import reverse
from django.db import models

# Create your models here.
class Producto(models.Model):
	producto = models.CharField(max_length=40)
	precio = models.IntegerField()
	descripcion = models.TextField()

	def __unicode__(self):
		return unicode(self.producto)
	#end def

	def get_absolute_url(self):
		return reverse('producto_update', kwargs={'pk': self.pk})
	#end def
#end class

class Cliente(models.Model):
	documento = models.IntegerField(unique=True)
	nombres = models.CharField(max_length=80)
	detalles = models.TextField(null=True, blank=True)

	def __unicode__(self):
		return unicode(self.nombres)
	#end def

	def get_absolute_url(self):
		return reverse('cliente_update', kwargs={'pk': self.pk})
	#end def
#end class

class Sede(models.Model):
	sede = models.CharField(max_length=40)
	direccion = models.CharField(max_length=40)

	def __unicode__(self):
		return unicode(self.sede)
	#end def

	def get_absolute_url(self):
		return reverse('sede_update', kwargs={'pk': self.pk})
	#end def
#end class

class Compra(models.Model):
	cliente = models.ForeignKey(Cliente, null=True, blank=True)
	producto = models.ForeignKey(Producto, null=True, blank=True)
	sede = models.ForeignKey(Sede, null=True, blank=True)
	precio = models.IntegerField(null=True, blank=True)
	descripcion = models.TextField(null=True, blank=True)
	fecha = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return unicode(self.producto)
	#end def

	def get_absolute_url(self):
		return reverse('compra_update', kwargs={'pk': self.pk})
	#end def
#end class

bitgray/tienda/forms.py
from django import forms
import models

class ProductoForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super(ProductoForm, self).__init__(*args, **kwargs)
		for myField in self.fields:
			self.fields[myField].widget.attrs['class'] = 'mdl-textfield__input'
		#end for
	#end def

	class Meta:
		model = models.Producto
		exclude = []
	#end class
#end class

class ClienteForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super(ClienteForm, self).__init__(*args, **kwargs)
		for myField in self.fields:
			self.fields[myField].widget.attrs['class'] = 'mdl-textfield__input'
		#end for
	#end def
	class Meta:
		model = models.Cliente
		exclude = []
	#end class
#end class

class SedeForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super(SedeForm, self).__init__(*args, **kwargs)
		for myField in self.fields:
			self.fields[myField].widget.attrs['class'] = 'mdl-textfield__input'
		#end for
	#end def
	class Meta:
		model = models.Sede
		exclude = []
	#end class
#end class

class CompraForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super(CompraForm, self).__init__(*args, **kwargs)
		for myField in self.fields:
			self.fields[myField].widget.attrs['class'] = 'mdl-textfield__input'
		#end for
	#end def
	class Meta:
		model = models.Compra
		exclude = []
	#end class
#end class

bitgray/tienda/views.py
from django.shortcuts import render, get_object_or_404
from django.core.mail import get_connection, EmailMultiAlternatives
from django.db import connection
from django.db.models import Case, Value, When, Sum, F, Avg, Max, Min, Count, Q
from django.db.models.expressions import RawSQL
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.core.urlresolvers import reverse_lazy
from xhtml2pdf import pisa
from django.template.loader import get_template
from django.template import Context
from django.http import HttpResponse
import cStringIO as StringIO
from cgi import escape
import json
import forms
import models
from bitgray import settings

# Create your views here.
def home(request):
	return render(request, 'dashboard/base.html')
#end def

class ProductoListView(ListView):
	model = models.Producto
#end class

class ProductoCreate(CreateView):
	template_name = "tienda/producto_add.html"
	form_class = forms.ProductoForm
	model = models.Producto
	exclude = []
#end class

class ProductoUpdate(UpdateView):
	template_name = "tienda/producto_edit.html"
	form_class = forms.ProductoForm
	model = models.Producto
	exclude = []
#end class

class ProductoDelete(DeleteView):
	model = models.Producto
	success_url = reverse_lazy('producto_list')
#end class


class ClienteListView(ListView):
	model = models.Cliente
#end class

class ClienteCreate(CreateView):
	template_name = "tienda/cliente_add.html"
	form_class = forms.ClienteForm
	model = models.Cliente
	exclude = []
#end class

class ClienteUpdate(UpdateView):
	template_name = "tienda/cliente_edit.html"
	form_class = forms.ClienteForm
	model = models.Cliente
	exclude = []
#end class

class ClienteDelete(DeleteView):
	model = models.Cliente
	success_url = reverse_lazy('cliente_list')
#end class

class SedeListView(ListView):
	model = models.Sede
#end class

class SedeCreate(CreateView):
	template_name = "tienda/sede_add.html"
	form_class = forms.SedeForm
	model = models.Sede
	exclude = []
#end class

class SedeUpdate(UpdateView):
	template_name = "tienda/sede_edit.html"
	form_class = forms.SedeForm
	model = models.Sede
	exclude = []
#end class

class SedeDelete(DeleteView):
	model = models.Sede
	success_url = reverse_lazy('sede_list')
#end class

class CompraListView(ListView):
	model = models.Compra
#end class

class CompraCreate(CreateView):
	template_name = "tienda/compra_add.html"
	form_class = forms.CompraForm
	model = models.Compra
	exclude = []
#end class

class CompraUpdate(UpdateView):
	template_name = "tienda/compra_edit.html"
	form_class = forms.CompraForm
	model = models.Compra
	exclude = []
#end class

class CompraDelete(DeleteView):
	model = models.Compra
	success_url = reverse_lazy('compra_list')
#end class

def consulta(request):
	compras = None
	cliente = None
	documento = None
	total = None
	error = False
	if request.method == 'POST' and request.POST.get('documento', False):
		documento = request.POST.get('documento', False)
		compras = models.Compra.objects.filter(cliente__documento=documento).exclude(producto=None).annotate(subtotal=Case(When(precio=None, then='producto__precio'), default='precio'))
		total = compras.aggregate(total=Sum('subtotal'))
		cliente = models.Cliente.objects.filter(documento=documento).first()
		error = cliente is None
	#end if
	return render(request, 'tienda/consulta.html', {'compras': compras, 'cliente': cliente, 'documento':documento , 'error':error, 'total':total})
#end def

def render_to_pdf(template_src, context_dict):
	template = get_template(template_src)
	context = Context(context_dict)
	html  = template.render(context)
	result = StringIO.StringIO()

	pdf = pisa.pisaDocument(StringIO.StringIO(html.encode("ISO-8859-1")), result)
	if not pdf.err:
		return HttpResponse(result.getvalue(), content_type='application/pdf')
	#end if
	return HttpResponse('We had some errors<pre>%s</pre>' % escape(html))
#end def

def cliente_pdf(request,pk):
	cliente = get_object_or_404(models.Cliente, pk=pk)
	compras = models.Compra.objects.filter(cliente=cliente).exclude(producto=None).annotate(subtotal=Case(When(precio=None, then='producto__precio'), default='precio'))
	total = compras.aggregate(total=Sum('subtotal'))
	return render_to_pdf(
		'tienda/cliente_compras_pdf.html',
		{
			'pagesize':'A4',
			'compras':compras,
			'cliente':cliente,
			'total':total
		}
	)
#end def

def cliente_json(request,pk):
	cliente = get_object_or_404(models.Cliente, pk=pk)
	compras = models.Compra.objects.filter(cliente=cliente).exclude(producto=None).annotate(subtotal=Case(When(precio=None, then='producto__precio'), default='precio'))
	total = compras.aggregate(total=Sum('subtotal'))
	compras = [{
		'id_productos':compra.producto.pk,
		'producto':compra.producto.producto,
		'sede': print_or_none(compra.sede),
		'precio':compra.subtotal
	} for compra in compras]

	data = {
		'documento': cliente.documento,
		'nombres': cliente.nombres,
		'compras': compras,
		'total': total['total']
	}
	return HttpResponse(json.dumps(data), content_type='application/json')
#end def

def print_or_none(object):
	if object:
		return str(object)
	else:
		return None
	#end if
#end def

def mailer(request):
	#data = models.Compra.objects.annotate(diferencia=(Case(When(precio=None, then=0), default=F('producto__precio') - F('precio')))).values('diferencia', 'precio', 'producto__precio')
	data = models.Compra.objects.exclude(producto=None).aggregate(
		diferencia_avg=Avg(Case(When(precio=None, then=0), default=F('producto__precio') - F('precio'))),
		diferencia_max=Max(Case(When(precio=None, then=0), default=F('producto__precio') - F('precio'))),
		diferencia_mim=Min(Case(When(precio=None, then=0), default=F('producto__precio') - F('precio'))),
		ganacias=Sum(Case(When(precio=None, then='producto__precio'), default='precio'))
	)
	data = dict(data)
	data['compras_por_min'] = compras_por_min()
	subject, from_email, to = 'Reporte semanal', settings.EMAIL_HOST_USER, settings.EMAIL_DESTINO
	text_content = 'Este es el reporte semanal de la tienda bitgray \n\n-diferencia promedio: %s \n-diferencia maxima: %s \n-diferencia minima: %s \n-ganacias: %s \n-promedio de ventas por minuto: %s' % (data['diferencia_avg'], data['diferencia_max'], data['diferencia_mim'], data['ganacias'], data['compras_por_min'])
	msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
	msg.send()
	return HttpResponse("ok")
#end def

def compras_por_min():
	cursor = connection.cursor()
	cursor.execute('select avg(num) as promedio from (SELECT date_format(fecha, "%Y-%m-%d %H:%i") as fecha_f, count(id) as num FROM tienda_compra group by fecha_f) as t')
	row = cursor.fetchone()
	return float(row[0])
#end def

bitgray/tienda/templates/tienda/cliente_add.html
{% extends "dashboard/base.html" %}
{% block title %}
	Clientes
{% endblock title %}
{% block content %}
	<style type="text/css">
		.send{
			float: right;
		}
		.delete{
			float: left;
			background: #de3226;
			color: #fff !important;
		}
	</style>
	<form action="" method="post">
		{% csrf_token %}
		{% for hidden in form.hidden_fields %}
		{{ hidden }}
		{% endfor %}
	<div class="mdl-grid">
		<div class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--10-col">
			<div class="mdl-card__title mdl-card--border">
				<h2 class="mdl-card__title-text">Agregar Cliente</h2>
			</div>
			<div class="mdl-card__supporting-text">
				<div class="mdl-grid">
				{% for field in form.visible_fields  %}
				{% if field.errors %}
					<style type="text/css">
						#{{ field.id_for_label }}{
							border-color: #de3226;
    						box-shadow: none;
						}
						label[for="{{ field.id_for_label }}"]{
							color: #de3226;
    						font-size: 12px;
						}
					</style>
				{% endif %}
					<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
						{{ field}}
						<label class="mdl-textfield__label" for="{{ field.id_for_label }}" >{{ field.label }}</label>
						{% for error in field.errors %}<span class="mdl-textfield__error" style="visibility: visible;">{{error}}</span>{% endfor %}
					</div>
				{% endfor %}
				</div>
			</div>
			<div class="mdl-card__actions mdl-card--border">
				<button class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect send">
					Enviar
				</button>
			</div>
		</div>
	</div>
	</form>
{% endblock content %}

bitgray/tienda/templates/tienda/cliente_confirm_delete.html
{% extends "dashboard/base.html" %}
{% block title %}
	Clientes
{% endblock title %}
{% block content %}
<style type="text/css">
	.delete{
		float: left;
		background: #de3226;
		color: #fff !important;
	}
</style>
<form action="" method="post">{% csrf_token %}
<div class="mdl-grid">
	<div class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--6-col">
		<div class="mdl-card__title mdl-card--border">
			<h2 class="mdl-card__title-text">¿Esta seguro de querer borrar el cliente {{ object }}?</h2>
		</div>
		<div class="mdl-grid">
		</div>
		<div class="mdl-card__actions">
			<button class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect delete">
				Eliminar
			</button>
		</div>
	</div>
</div>
{% endblock content %}

bitgray/tienda/templates/tienda/cliente_edit.html
{% extends "dashboard/base.html" %}
{% block title %}
	Clientes
{% endblock title %}
{% block content %}
	<style type="text/css">
		.send{
			float: right;
		}
		.delete{
			float: left;
			background: #de3226;
			color: #fff !important;
		}
	</style>
	<form action="" method="post">
		{% csrf_token %}
		{% for hidden in form.hidden_fields %}
		{{ hidden }}
		{% endfor %}
	<div class="mdl-grid">
		<div class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--10-col">
			<div class="mdl-card__title mdl-card--border">
				<h2 class="mdl-card__title-text">Editar Cliente</h2>
			</div>
			<div class="mdl-card__supporting-text">
				<div class="mdl-grid">
				{% for field in form.visible_fields  %}
				{% if field.errors %}
					<style type="text/css">
						#{{ field.id_for_label }}{
							border-color: #de3226;
    						box-shadow: none;
						}
						label[for="{{ field.id_for_label }}"]{
							color: #de3226;
    						font-size: 12px;
						}
					</style>
				{% endif %}
					<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
						{{ field}}
						<label class="mdl-textfield__label" for="{{ field.id_for_label }}" >{{ field.label }}</label>
						{% for error in field.errors %}<span class="mdl-textfield__error" style="visibility: visible;">{{error}}</span>{% endfor %}
					</div>
				{% endfor %}
				</div>
			</div>
			<div class="mdl-card__actions mdl-card--border">
				<a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect delete" href="{% url 'cliente_delete' pk=object.pk %}">
      				Eliminar
    			</a>
				<button class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect send">
					Enviar
				</button>
			</div>
		</div>
	</div>
	</form>
{% endblock content %}

bitgray/tienda/templates/tienda/compra_add.html
{% extends "dashboard/base.html" %}
{% block title %}
	Compras
{% endblock title %}
{% block content %}
	<style type="text/css">
		.send{
			float: right;
		}
		.delete{
			float: left;
			background: #de3226;
			color: #fff !important;
		}
		label[for="id_cliente"], label[for="id_producto"], label[for="id_sede"]{
			top: 4px !important;
			visibility: visible;
			font-size: 12px;
		}
	</style>
	<form action="" method="post">
		{% csrf_token %}
		{% for hidden in form.hidden_fields %}
		{{ hidden }}
		{% endfor %}
	<div class="mdl-grid">
		<div class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--10-col">
			<div class="mdl-card__title mdl-card--border">
				<h2 class="mdl-card__title-text">Agregar Compra</h2>
			</div>
			<div class="mdl-card__supporting-text">
				<div class="mdl-grid">
				{% for field in form.visible_fields  %}
				{% if field.errors %}
					<style type="text/css">
						#{{ field.id_for_label }}{
							border-color: #de3226;
    						box-shadow: none;
						}
						label[for="{{ field.id_for_label }}"]{
							color: #de3226;
    						font-size: 12px;
						}
					</style>
				{% endif %}
					<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
						{{ field}}
						<label class="mdl-textfield__label" for="{{ field.id_for_label }}" >{{ field.label }}</label>
						{% for error in field.errors %}<span class="mdl-textfield__error" style="visibility: visible;">{{error}}</span>{% endfor %}
					</div>
				{% endfor %}
				</div>
			</div>
			<div class="mdl-card__actions mdl-card--border">
				<button class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect send">
					Enviar
				</button>
			</div>
		</div>
	</div>
	</form>
{% endblock content %}

bitgray/tienda/templates/tienda/compra_confirm_delete.html
{% extends "dashboard/base.html" %}
{% block title %}
	Compras
{% endblock title %}
{% block content %}
<style type="text/css">
	.delete{
		float: left;
		background: #de3226;
		color: #fff !important;
	}
</style>
<form action="" method="post">{% csrf_token %}
<div class="mdl-grid">
	<div class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--6-col">
		<div class="mdl-card__title mdl-card--border">
			<h2 class="mdl-card__title-text">¿Esta seguro de querer borrar la compra {{ object }}?</h2>
		</div>
		<div class="mdl-grid">
		</div>
		<div class="mdl-card__actions">
			<button class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect delete">
				Eliminar
			</button>
		</div>
	</div>
</div>
{% endblock content %}

bitgray/tienda/templates/tienda/compra_edit.html
{% extends "dashboard/base.html" %}
{% block title %}
	Compras
{% endblock title %}
{% block content %}
	<style type="text/css">
		.send{
			float: right;
		}
		.delete{
			float: left;
			background: #de3226;
			color: #fff !important;
		}
	</style>
	<form action="" method="post">
		{% csrf_token %}
		{% for hidden in form.hidden_fields %}
		{{ hidden }}
		{% endfor %}
	<div class="mdl-grid">
		<div class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--10-col">
			<div class="mdl-card__title mdl-card--border">
				<h2 class="mdl-card__title-text">Editar Compra</h2>
			</div>
			<div class="mdl-card__supporting-text">
				<div class="mdl-grid">
				{% for field in form.visible_fields  %}
				{% if field.errors %}
					<style type="text/css">
						#{{ field.id_for_label }}{
							border-color: #de3226;
    						box-shadow: none;
						}
						label[for="{{ field.id_for_label }}"]{
							color: #de3226;
    						font-size: 12px;
						}
					</style>
				{% endif %}
					<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
						{{ field}}
						<label class="mdl-textfield__label" for="{{ field.id_for_label }}" >{{ field.label }}</label>
						{% for error in field.errors %}<span class="mdl-textfield__error" style="visibility: visible;">{{error}}</span>{% endfor %}
					</div>
				{% endfor %}
				</div>
			</div>
			<div class="mdl-card__actions mdl-card--border">
				<a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect delete" href="{% url 'compra_delete' pk=object.pk %}">
      				Eliminar
    			</a>
				<button class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect send">
					Enviar
				</button>
			</div>
		</div>
	</div>
	</form>
{% endblock content %}

bitgray/tienda/templates/tienda/compra_list.html
{% extends "dashboard/base.html" %}
{% block title %}
	Compras
{% endblock title %}
{% block content %}
<style type="text/css">
	#add {
	    position: fixed;
	    display: block;
	    right: 0;
	    bottom: 0;
	    margin-right: 40px;
	    margin-bottom: 40px;
	    z-index: 900;
	}
</style>
<div class="mdl-grid">
	<table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp mdl-cell ">
	  <thead>
	    <tr>
	    	<th class="mdl-data-table__cell--non-numeric">Cliente</th>
	    	<th class="mdl-data-table__cell--non-numeric">Sede</th>
	    	<th class="mdl-data-table__cell--non-numeric">Producto</th>
	    	<th>Precio</th>
	    	<th class="mdl-data-table__cell--non-numeric">Fecha</th>
	    </tr>
	  </thead>
	  <tbody>
	  	{% for compra in object_list %}
		<tr>
	      <td class="mdl-data-table__cell--non-numeric"><a href="{% url 'compra_update' pk=compra.pk %}">{{ compra.cliente }}</a></td>
	      <td class="mdl-data-table__cell--non-numeric">{% if compra.sede %}{{ compra.sede }}{% else %}Sin sede{% endif %}</td>
	      <td class="mdl-data-table__cell--non-numeric">{{ compra.producto }}</td>
	      <td>${% if compra.precio %}{{ compra.precio }}{% else %}{{ compra.producto.precio }}{% endif %}</td>
	      <td class="mdl-data-table__cell--non-numeric">{{ compra.fecha }}</td>
	    </tr>    
		{% empty %}
		    <li>No articles yet.</li>
		{% endfor %}
	    
	  </tbody>
	</table>
</div>
<a class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored mdl-shadow--2dp" id="add" href="{% url 'compra_add' %}">
  <i class="material-icons">add</i>
</a>
{% endblock content %}

bitgray/tienda/templates/tienda/producto_add.html
{% extends "dashboard/base.html" %}
{% block title %}
	Productos
{% endblock title %}
{% block content %}
	<style type="text/css">
		.send{
			float: right;
		}
		.delete{
			float: left;
			background: #de3226;
			color: #fff !important;
		}
	</style>
	<form action="" method="post">
		{% csrf_token %}
		{% for hidden in form.hidden_fields %}
		{{ hidden }}
		{% endfor %}
	<div class="mdl-grid">
		<div class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--10-col">
			<div class="mdl-card__title mdl-card--border">
				<h2 class="mdl-card__title-text">Agregar Producto</h2>
			</div>
			<div class="mdl-card__supporting-text">
				<div class="mdl-grid">
				{% for field in form.visible_fields  %}
				{% if field.errors %}
					<style type="text/css">
						#{{ field.id_for_label }}{
							border-color: #de3226;
    						box-shadow: none;
						}
						label[for="{{ field.id_for_label }}"]{
							color: #de3226;
    						font-size: 12px;
						}
					</style>
				{% endif %}
					<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
						{{ field}}
						<label class="mdl-textfield__label" for="{{ field.id_for_label }}" >{{ field.label }}</label>
						{% for error in field.errors %}<span class="mdl-textfield__error" style="visibility: visible;">{{error}}</span>{% endfor %}
					</div>
				{% endfor %}
				</div>
			</div>
			<div class="mdl-card__actions mdl-card--border">
				<button class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect send">
					Enviar
				</button>
			</div>
		</div>
	</div>
	</form>
{% endblock content %}

bitgray/tienda/templates/tienda/producto_confirm_delete.html
{% extends "dashboard/base.html" %}
{% block title %}
	Productos
{% endblock title %}
{% block content %}
<style type="text/css">
	.delete{
		float: left;
		background: #de3226;
		color: #fff !important;
	}
</style>
<form action="" method="post">{% csrf_token %}
<div class="mdl-grid">
	<div class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--6-col">
		<div class="mdl-card__title mdl-card--border">
			<h2 class="mdl-card__title-text">¿Esta seguro de querer borrar el producto {{ object }}?</h2>
		</div>
		<div class="mdl-grid">
		</div>
		<div class="mdl-card__actions">
			<button class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect delete">
				Eliminar
			</button>
		</div>
	</div>
</div>
{% endblock content %}